fixes #3, added type to hotspot update call
fruitnanny/fruitnanny-api pull request #4
Opened 2020-06-17 08:55 UTC by PretentiousPotatoPeeler

2020-06-17 14:52 UTC, kahlertl requested changes
Thanks for the pull request :smiley: I think it can be even simpler by just allowing the `type` field in the JSON payload and just ignore it afterwards.

Besides this, can you reiterate on your commit message and be a little bit more verbose?

![xkcd: git commit messages](https://imgs.xkcd.com/comics/git_commit.png)

Personally, I try to follow these rules https://chris.beams.io/posts/git-commit/

2020-06-17 14:52 UTC, f3anaro commented on internal/api/network.go
> +func (nm *NetworkManager) UpdateHotspot(hotspot *Hotspot, ssid string, password *string, typeStr string) error {
Since the type of the hotspot can never change, we do not need to pass it along the `UpdateHotspot` function.

2020-06-17 14:54 UTC, f3anaro commented
Btw, I you want to have a quick path forward, I can also fix the issue and create a release today?

2020-06-18 05:53 UTC, PretentiousPotatoPeeler commented
Fair points! Also an interesting article about commit messages. I'll move some stuff around and submit a new pull request. 

You're of course free to fix the bug yourself, but I'd love to contribute to the project. I'll submit the new pull request today

2020-06-18 05:53 UTC, closed without merging

2020-06-18 06:37 UTC, f3anaro commented
No rush, I will wait for your contribution :smile: 

Btw, you can also salvage this pull request. No need to create a complete new one. I suggest that you just reopen this one once you have a new patch.

2020-06-18 07:25 UTC, PretentiousPotatoPeeler commented
I've recreated the branch so the pull request can't be reopened. #5 is the new PR